### ISSUE TITLE
sync with git? 

### ISSUE THREAD

**Issue by anwar3606** [bangle-io/bangle-io#223]
Is it possible to introduce automatic commit & push for any changes made? 

I have to use it on multiple computers, manually committing & pushing is not ergonomic, and I will easily forget.

**Comment by kepta** [comment]
Automatic commit and push will be hard within the realm of browser, as it GitHub does not support CORS (see https://github.com/isomorphic-git/isomorphic-git#cors-support). That said I am planning to introduce syncing with Github using their API and personal access token, do you think that will help with what your original ask?

**Comment by anwar3606** [comment]
If that possible that will be really useful

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zanetaylor** [comment]
That would be fantastic, and the perfect syncing solution for me.

**Comment by kepta** [comment]
This is now supported 🥳 with Github . Let me know if you have feedback regarding this.
