### ISSUE TITLE
Request for Local File System Workspace support in Firefox

### ISSUE THREAD

**Issue by bumper314** [bangle-io/bangle-io#226]
I would like Local File System Workspace support for Firefox.  I'm mostly just creating this request so others can chime in if they too want to see this feature.

**Comment by kepta** [comment]
Similar to https://github.com/bangle-io/bangle-io/issues/225, The folks at Mozilla have marked this feature dangerous even after multiple devs, including me (see https://github.com/mozilla/standards-positions/issues/154#issuecomment-860952889), voiced how important it is for the web ecosystem. 😞

**Comment by bumper314** [comment]
Good to know.  At the very least, this request can serve as a search hit for anyone who might request this in the future… the increasingly bleak future where large tech oligopolies tell users what users want and restrict developers means of creation.  Good luck to you sir.
