### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Erik-Nickel** [bangle-io/bangle-io#328]
Is it possible to add support for firefox so the app works as it does on Chromium based browsers?
Currently:
- I can not save the workspace locally on Firefox.
- Crtl + Shift + P opens a news ivate browsing window

**Comment by kepta** [comment]
Hey thanks for opening a ticket.

> I can not save the workspace locally on Firefox.

There is an issue with Firefox where they are not interesting in implementing file storage , see https://github.com/bangle-io/bangle-io/issues/226.

> Crtl + Shift + P opens a news private browsing window

For Firefox you will have to press the following keys:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/6966254/164367989-b55466ee-093a-49a1-a437-812a46191127.png">
