### ISSUE TITLE
Implement Nextcloud Collective Integration

### ISSUE THREAD

**Issue by compgeniuses** [bangle-io/bangle-io#329]
Nextcloud Provides Nextcloud Collectives as a sort of wiki/ documentation tool, unfortunately, it is only available online and only editable through the nextcloud browser. https://apps.nextcloud.com/apps/collectives
this solution is great, works with Markdown and Saves Documents and Files locally.

How About, implementing the App, in such a manner that it work with Nextcloud Collectives, using their Folder Structure, or providing a from of sync mechanism, so that the locally stored Nextcloud Collective files, can be edited within Bangle. that way, this becomes the Defactor Nextcloud Collectives offline tools.

This will increase the update of the project, and Most nextcloud Collectives users, would install this for Offline Support.

**Comment by kepta** [comment]
I dont think I will be able to look into this as it doesn't align with the projects direction.
