### ISSUE TITLE
Support for android arm64?

### ISSUE THREAD

**Issue by GiancarloAparicio** [bangle-io/bangle-io#339]
Hi, I know bangle wasn't meant to run on Android, but I really like the idea of using my phone with termux as a server.
When I want to build bangle I get the following error:
![image](https://user-images.githubusercontent.com/61440825/168336182-1e804af6-5666-4ef3-b2b9-a6fe09f678fd.png)

Node: v16.14.2

**Comment by kepta** [comment]
Can you try removing `sentry` from package.json and see if it compiles?

**Comment by GiancarloAparicio** [comment]
it works, removing all sentry dependencies :)
