### ISSUE TITLE
Unable to create workspace from filesystem

### ISSUE THREAD

**Issue by Flashwalker** [bangle-io/bangle-io#400]
```
Unable to create workspace ...
￼
assertion failed: workspacesInfo cannot be undefined
```
browser: Ungoogled Chromium v.105

**Comment by Flashwalker** [comment]
The same with workspace in browser db

**Comment by Flashwalker** [comment]
Also:
```
Error:Unable to handler error Workspace bangle not found
```

**Comment by kepta** [comment]
Hey thanks for opening this issue. I am finding it hard to reproduce, do you mind provide the following details:
- Your browsers console logs when this error shows up. (you can right click anywhere and click inspect to see the console show up).
- Are you using any extensions? Can you seeing this problem in incognito?

**Comment by Flashwalker** [comment]
> Hey thanks for opening this issue. I am finding it hard to reproduce, do you mind providing the following details:
> 
> * Your browsers console logs when this error shows up (you can right click anywhere and click `inspect` to see the console show up).
> * Are you using any extensions? Can you see this problem in incognito?

Don't know what happened, but now it works again and see my folder and notes

**Comment by Flashwalker** [comment]
I found that the problem appeared when I created a fresh profile for my ungoogled-chromium browser and tried to access the bangle folder created in another profile.
But yesterday I tried again and there were no errors.

**Comment by kepta** [comment]
Let me know if you face this issue again.
