### ISSUE TITLE
Recognize also Brave browser as a Chromium-based browser

### ISSUE THREAD

**Issue by fsoft72** [bangle-io/bangle-io#408]
In Brave browser, it is not possible to create local Filesystem workspaces, because Brave is not recognized as a Chromium-based browser (but it is).

**Comment by kepta** [comment]
Hey thanks for opening this ticket. Last I remember brave decided to not support file system storage. 

I guess you can enable it by turning on a flag as per https://github.com/brave/brave-browser/issues/20563  . 

Let me know if that works, I can add some documentation for it.

**Comment by fsoft72** [comment]
Yes, it works!

Thanks, now I can use your great app on Brave :-)
