### ISSUE TITLE
Unable to create note in Edge browser

### ISSUE THREAD

**Issue by IvorkChan** [bangle-io/bangle-io#419]
Windows 11, Edge

After selecting a local directory as workspace, everytime I try to create note, I get an error like this:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/19368630/203979953-ead1497c-ff70-4f82-afec-8cded73d51ce.png">

**Comment by kepta** [comment]
This was really nice of you to report @IvorkChan ! I had no idea this was broken for the past few weeks.
